# Generated by Django 5.2 on 2025-04-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_type', models.CharField(choices=[('Hourly', 'Hourly'), ('Fixed Price', 'Fixed Price')], default=None, max_length=20)),
                ('billing_cadence', models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Fixed Date', 'Fixed Date')], default=None, max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.client')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Done', 'Done')], default='To Do', max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Hosting', 'Hosting'), ('Material', 'Material'), ('Licensing', 'Licensing'), ('Other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.contract')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Done', 'Done')], default='To Do', max_length=20)),
                ('due_date', models.DateField()),
                ('ready_to_invoice', models.BooleanField(default=False)),
                ('invoiced', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.contract')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('revenue_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable')], max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Canceled', 'Canceled')], default='Draft', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.contract')),
                ('tasks', models.ManyToManyField(blank=True, to='execution.task')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='execution.invoice')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='execution.task')),
            ],
        ),
    ]
