# Generated by Django 5.2 on 2025-04-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_client_address_client_created_at_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email_invoice',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
