# Generated by Django 5.2 on 2025-04-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_client_contact_email_client_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
